version: "3.1"
services:
  app:
    build: ./docker
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - mvcapp

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mvcapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - mvcapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mvcapp

networks:
  mvcapp:
    driver: bridge

volumes:
  persistent:
